@startuml class

' クラス定義

class クライアント
{
クライアント
}

class サーバー
{
クライアント通信クラス
}

class 翻訳機
{
メッセージ変換、処理関数呼び出しクラス
}

class ユーザー
{
ユーザー管理クラス
}

class チャンネル
{
チャンネル管理クラス
}

' 関係（サーバー ← 翻訳機 ← ユーザー）
クライアント<-->サーバー
サーバー <.. 翻訳機
翻訳機 <.. ユーザー
翻訳機 <.. チャンネル
チャンネル<..ユーザー

@enduml
